### ISSUE TITLE
Error when running make clean all run platform=fpga

### ISSUE THREAD

**Issue by AnupamYedida** [pulp-platform/pulp-sdk#137]
Traceback (most recent call last):
  File "/home/innis226/prof_vivek_project/pulp-sdk/tools/gapy/gapy", line 26, in <module>
    from errors import FatalError, InputError
  File "/home/innis226/prof_vivek_project/pulp-sdk/tools/gapy/errors.py", line 21, in <module>
    import common
  File "/home/innis226/prof_vivek_project/pulp-sdk/tools/gapy/common.py", line 30, in <module>
    from tools.runner.runner import Runner
ModuleNotFoundError: No module named 'tools'
make: *** [/home/innis226/prof_vivek_project/pulp-sdk/rtos/pulpos/common/rules/pulpos/default_rules.mk:350: image] Error 1

I am trying to run the MobilenetV1 and this is the error I am getting. The same problem even with Hello world program. It is working fine with platform=gvsoc.

**Comment by GaDuKun** [comment]
Hi AnupamYedida,

I got the same problem. How di you resolve it?

**Comment by yoss0902** [comment]
Hi

i got the same problem, could you tell me how you solved it?

**Comment by GaDuKun** [comment]
Hi Yoss0902,

Perhaps you are using the branch master.
I overcomed this issue by using another branch ( on tag version 2022.07.22).
